apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 5
  # retries: 1
  metadata:
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA

xcuitest:
  app: Apps/DemoApp.ipa
  testApp: Apps/DemoAppUITests-Runner.ipa

suites:
  - name: "real-config-6 - sharding classes"
    shard: concurrency
    testListFile: DemoApp/test_real_classes.txt
    timeout: 10m
    devices:
      - name: "iPhone.*"
        platformVersion: "16"
artifacts:
  download:
    when: always
    match:
      - "junit.xml"
    directory: ./artifacts/
